RMS.MVC/Controllers/TableController.cs
using Microsoft.AspNetCore.Mvc;
using RMS.Service.DTOs.HallDTO;
using RMS.Service.DTOs.TableDTO;
using RMS.Service.Exceptions;
using RMS.Service.Services.Interfaces;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;

namespace RMS.MVC.Controllers
{
    public class TableController : Controller
    {
        private readonly ITableService _tableService;
        private readonly IHallService _hallService;

        public TableController(ITableService tableService, IHallService hallService)
        {
            _tableService = tableService;
            _hallService = hallService;
        }

        public async Task<IActionResult> Index()
        {
            TableGetAllDTO tables = await _tableService.GetAllAsync();
            return View(tables);
        }

        public async Task<IActionResult> Create()
        {
            HallGetAllDTO halls = await _hallService.GetAllAsync();
            ViewBag.Halls = halls.Halls;
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(TablePostDTO tableDTO)
        {
            HallGetAllDTO halls = await _hallService.GetAllAsync();
            ViewBag.Halls = halls.Halls;
            try
            {
                await _tableService.CreateAsync(tableDTO);
            }
            catch (AlreadyExistException ex)
            {
                ModelState.AddModelError("Number",ex.Message);
                return View();
            }
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Delete(int id)
        {
            await _tableService.Delete(id);
            return Json(new { status = 200 });
        }

        public async Task<IActionResult> Update(int id)
        {
            TableUpdateDTO tableDto = await _tableService.GetByIdAsync<TableUpdateDTO>(id);
            HallGetAllDTO halls = await _hallService.GetAllAsync();
            ViewBag.halls = halls.Halls;
            return View(tableDto);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Update(int id, TableUpdateDTO tabledto)
        {
            HallGetAllDTO halls = await _hallService.GetAllAsync();
            ViewBag.Halls = halls.Halls;
            if (!ModelState.IsValid)
            {
                return View();
            }
            await _tableService.EditAsync(id, tabledto);
            return RedirectToAction(nameof(Index));
        }
    }
}

RMS.MVC/Views/Table/Create.cshtml
@using RMS.Service.DTOs.TableDTO
@model TablePostDTO
@{
    ViewData["Title"] = "Create";
}

<div class="row">
    <div class="col-md-12 col-lg-12">
        <div class="card mb-4">
            <div class="card-header">
                <div class="d-flex justify-content-between align-items-center">
                    <div>
                        <h6 class="fs-17 font-weight-600 mb-0">Create Blog</h6>
                    </div>
                </div>
            </div>
            <div class="card-body">
                <form method="post" enctype="multipart/form-data">
                    <div class="form-group">
                        <label asp-for="Number" class="font-weight-600">Number</label>
                        <input class="form-control" placeholder="Number" asp-for="Number">
                        <span asp-validation-for="Number" class="text-danger">  </span>
                    </div>
                    <div class="form-group">
                        <label asp-for="AmountOfSeat" class="font-weight-600">Amount Of Seat</label>
                        <input class="form-control" placeholder="AmountOfSeat" asp-for="AmountOfSeat">
                        <span asp-validation-for="AmountOfSeat" class="text-danger">  </span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Deposite" class="font-weight-600">Deposite</label>
                        <input class="form-control" placeholder="Deposite" asp-for="Deposite"> </input>
                        <span asp-validation-for="Deposite" class="text-danger">  </span>
                    </div>
                    <div class="form-group" id="CategoryDiv">
                        <label asp-for="HallId">Hall</label>
                        <select class="form-control" name="HallId">
                            <option value="0">--Select Hall--</option>
                            @foreach (var item in ViewBag.Halls)
                            {
                                <option value="@item.Id">@item.Name</option>

                            }
                        </select>
                    </div>


                    <button type="submit" class="btn btn-success">Submit</button>
                    <a asp-action="Index" class="btn btn-light">Cancel</a>
                </form>
            </div>
        </div>
    </div>
</div>

RMS.MVC/Views/Table/Index.cshtml
@using RMS.Service.DTOs.TableDTO
@model TableGetAllDTO
@{
    ViewData["Title"] = "Index";
}

<div class="col-lg-12">
    <div class="card mb-4">

        <div class="card-body">
            <h3>Tables</h3>
            <a class="btn btn-success mb-3" asp-controller="Table" asp-action="Create">Create</a>

            <div class="table-responsive">
                <table class="table">
                    <thead class="thead-dark">
                        <tr>
                            <th scope="col">Table Number</th>
                            <th scope="col">Table Status</th>
                            <th scope="col">Deposite</th>
                            <th scope="col">Amount of Seat</th>
                            <th scope="col">Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model.Tables)
                        {
                        <tr>
                            <td>@item.Number</td>
                            <td>@item.Status</td>
                            <td>@item.Deposite</td>
                            <td>@item.AmountOfSeat</td>
                            <td>
                                <a class="btn btn-warning" asp-controller="Table" asp-action="Update" asp-route-id="@item.Id">Update</a>
                                <a class="btn btn-danger delete-item" asp-controller="Table" asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                            </td>
                        </tr>
                        }

                    </tbody>
                </table>

            </div>
        </div>
    </div>
</div>

@section Scripts{
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>

    <script>
        $(document).ready(function () {
            $(".delete-item").click(function (ev) {
                ev.preventDefault();
                Swal.fire({
                    title: 'Are you sure?',
                    text: "You won't be able to revert this!",
                    icon: 'warning',
                    showCancelButton: true,
                    confirmButtonColor: '#3085d6',
                    cancelButtonColor: '#d33',
                    confirmButtonText: 'Yes, delete it!'
                }).then((result) => {
                    if (result.isConfirmed) {
                        let link = $(this).attr("href")
                        fetch(link).then(response => response.json()).then(data => {
                            if (data.status == 200) {
                                Swal.fire(
                                    'Deleted!',
                                    'Your file has been deleted.',
                                    'success'
                                )
                                setTimeout(() =>
                                { location.reload(true) }, 1000);
                            }
                            else {
                                Swal.fire(
                                    'Error!',
                                    'Your file not Found.',
                                    'Failed'
                                )
                            }
                        })

                    }
                })
            })
        })
    </script>
} 

RMS.MVC/Views/Table/Update.cshtml
@using RMS.Service.DTOs.TableDTO
@model TableUpdateDTO
@{
    ViewData["Title"] = "Create";
}
<div class="row">
    <div class="col-md-12 col-lg-12">
        <div class="card mb-4">
            <div class="card-header">
                <div class="d-flex justify-content-between align-items-center">
                    <div>
                        <h6 class="fs-17 font-weight-600 mb-0">Create Hall</h6>
                    </div>
                </div>
            </div>
            <div class="card-body">
                <form method="post">
                    <div class="form-group">
                        <label asp-for="Number" class="font-weight-600">Number</label>
                        <input class="form-control" placeholder="Number" asp-for="Number">
                        <span asp-validation-for="Number" class="text-danger">  </span>
                    </div>
                    <div class="form-group">
                        <label asp-for="AmountOfSeat" class="font-weight-600">AmountOfSeat</label>
                        <input class="form-control" placeholder="AmountOfSeat" asp-for="AmountOfSeat">
                        <span asp-validation-for="AmountOfSeat" class="text-danger">  </span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Deposite" class="font-weight-600">Deposite</label>
                        <input class="form-control" placeholder="Deposite" asp-for="Deposite">
                        <span asp-validation-for="Deposite" class="text-danger">  </span>
                    </div>
                    <div class="form-group">
                        <label asp-for="HasDeposite" class="font-weight-600">HasDeposite</label>
                        <input class="form-control" placeholder="HasDeposite" asp-for="HasDeposite">
                        <span asp-validation-for="HasDeposite" class="text-danger">  </span>
                    </div>
                    <div class="form-group">
                        <label asp-for="HallId" class="font-weight-600">Hall</label>
                        <select class="form-control" name="HallId">
                            <option value="0">--Select Hall-- </option>
                            @foreach (var item in ViewBag.halls)
                            {
                                if (item.Id == Model.HallId)
                                {
                                    <option value="@item.Id" selected>@item.Name</option>

                                }
                                else
                                {
                                    <option value="@item.Id">@item.Name</option>
                                }
                            }
                        </select>
                    </div>

                    <button type="submit" class="btn btn-success">Submit</button>
                    <a asp-action="Index" class="btn btn-light">Cancel</a>
                </form>
            </div>
        </div>
    </div>
</div>

@section Scripts{
    <partial name="_ValidationScriptsPartial" />
}