RMS.MVC/Controllers/FoodController.cs
using Microsoft.AspNetCore.Mvc;
using RMS.Service.DTOs;
using RMS.Service.DTOs.CategoryDTO;
using RMS.Service.DTOs.FoodDTO;
using RMS.Service.Exceptions;
using RMS.Service.Services.Interfaces;
using System.Net;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;

namespace RMS.MVC.Controllers
{
    public class FoodController : Controller
    {
        private readonly IFoodService _foodService;
        private readonly ICategoryService _categoryService;

        public FoodController(IFoodService foodService, ICategoryService categoryService)
        {
            _foodService = foodService;
            _categoryService = categoryService;
        }

        public async Task<IActionResult> Index(int pageIndex = 1,int count = 10)
        {
            PagenatedListDTO<FoodGetDTO> foods = await _foodService.GetAllFilteredAsync(pageIndex, count);
            return View(foods);
        }

        public async Task<IActionResult> Create()
        {
            CategoryGetAllDTO<CategoryGetDTO> categories = await _categoryService.GetAllAsync<CategoryGetDTO>();
            ViewBag.Categories = categories.Categories;
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(FoodPostDTO foodDto)
        {
            CategoryGetAllDTO<CategoryGetDTO> categories = await _categoryService.GetAllAsync<CategoryGetDTO>();
            ViewBag.Categories = categories.Categories;
            if (!ModelState.IsValid)
            {
                return View();
            }
            try
            {
                await _foodService.CreateAsync(foodDto);
            }
            catch (AlreadyExistException ex)
            {
                ModelState.AddModelError("Name", ex.Message);
                return View();

            }
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Delete(int id)
        {
            await _foodService.Delete(id);
            return Json(new { status = 200 });
        }

        public async Task<IActionResult> Update(int id)
        {
            CategoryGetAllDTO<CategoryGetDTO> categories = await _categoryService.GetAllAsync<CategoryGetDTO>();
            ViewBag.Categories = categories.Categories;
            FoodEditDTO foodDto = await _foodService.GetByIdAsync<FoodEditDTO>(id);
            return View(foodDto);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Update(int id , FoodEditDTO foodDto) {
            CategoryGetAllDTO<CategoryGetDTO> categories = await _categoryService.GetAllAsync<CategoryGetDTO>();
            ViewBag.Categories = categories.Categories;
            if (!ModelState.IsValid)
            {
                return View();
            }
            await _foodService.EditAsync(id, foodDto);
            return RedirectToAction(nameof(Index));
        }
    }
}

RMS.MVC/Views/Food/Create.cshtml
@using RMS.Service.DTOs.FoodDTO
@model FoodPostDTO
@{
    ViewData["Title"] = "Create";
}
<div class="row">
    <div class="col-md-12 col-lg-12">
        <div class="card mb-4">
            <div class="card-header">
                <div class="d-flex justify-content-between align-items-center">
                    <div>
                        <h6 class="fs-17 font-weight-600 mb-0">Create Category</h6>
                    </div>
                </div>
            </div>
            <div class="card-body">
                <form method="post" enctype="multipart/form-data">
                    <div class="form-group" >
                        <label asp-for="Name" class="font-weight-600">Name</label>
                        <input  class="form-control"  placeholder="Name" asp-for="Name">
                        <span asp-validation-for="Name" class="text-danger">  </span>
                    </div>
                    <div class="form-group" >
                        <label asp-for="Price" class="font-weight-600">Price</label>
                        <input  class="form-control"  placeholder="Name" asp-for="Price">
                        <span asp-validation-for="Price" class="text-danger">  </span>
                    </div>
                    <div class="form-group" id="CategoryDiv">
                        <label asp-for="CategoryId">Hall</label>
                        <select class="form-control" name="CategoryId">
                            <option value="0">--Select CAtegory--</option>
                            @foreach (var item in ViewBag.Categories)
                            {
                                <option value="@item.Id">@item.Name</option>

                            }
                        </select>
                    </div>
                    <div class="form-group">
                        <label asp-for="File" class="font-weight-600">Photo</label>
                        <input class="form-control" placeholder="Photo" asp-for="File" accept="image/*">
                        <span asp-validation-for="File" class="text-danger">  </span>
                    </div>
                    
                    <button type="submit" class="btn btn-success">Submit</button>
                    <a asp-action="Index" class="btn btn-light">Cancel</a>
                </form>
            </div>
        </div>
    </div>
</div>

RMS.MVC/Views/Food/Index.cshtml
@using RMS.Service.DTOs.FoodDTO
@using RMS.Service.DTOs

@model PagenatedListDTO<FoodGetDTO>
@{
    ViewData["Title"] = "Index";
}

<div class="col-lg-12">
    <div class="card mb-4">
        <div class="card-body">
            <h3>Foods</h3>
            <a class="btn btn-success mb-3" asp-controller="Food" asp-action="Create">Create</a>

            <div class="table-responsive">
                <table class="table">
                    <thead class="thead-dark">
                        <tr>
                            <th scope="col">Image</th>
                            <th scope="col">Name</th>
                            <th scope="col">Category</th>
                            <th scope="col">Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model.Items)
                        {
                            <tr>
                                <td><img src="@item.File" style="width:50px; height:50px" /></td>
                                <td>@item.Name</td>
                                <td>@item.Category</td>
                                <td>
                                    <a class="btn btn-warning" asp-controller="Food" asp-action="Update" asp-route-id="@item.Id">Update</a>
                                    <a class="btn btn-success" asp-controller="Food" asp-action="Detail" asp-route-id="@item.Id">Details</a>
                                    <a class="btn btn-danger delete-item" asp-controller="Food" asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
@section Scripts{
     <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    
    <script>
        $(document).ready(function () {
            $(".delete-item").click(function (ev) {
                ev.preventDefault();
                Swal.fire({
                    title: 'Are you sure?',
                    text: "You won't be able to revert this!",
                    icon: 'warning',
                    showCancelButton: true,
                    confirmButtonColor: '#3085d6',
                    cancelButtonColor: '#d33',
                    confirmButtonText: 'Yes, delete it!'
                }).then((result) => {
                    if (result.isConfirmed) {
                        let link = $(this).attr("href")
                        fetch(link).then(response => response.json()).then(data => {
                            if (data.status == 200) {
                                Swal.fire(
                                    'Deleted!',
                                    'Your file has been deleted.',
                                    'success'
                                )
                                setTimeout(() =>
                                { location.reload(true) }, 1000);
                            }
                            else {
                                Swal.fire(
                                    'Error!',
                                    'Your file not Found.',
                                    'Failed'
                                )
                            }
                        })
                     
                    }
                })
            })
        })
    </script>
 }

RMS.MVC/Views/Food/Update.cshtml
@using RMS.Service.DTOs.FoodDTO
@model FoodEditDTO
@{
    ViewData["Title"] = "Create";
}
<div class="row">
    <div class="col-md-12 col-lg-12">
        <div class="card mb-4">
            <div class="card-header">
                <div class="d-flex justify-content-between align-items-center">
                    <div>
                        <h6 class="fs-17 font-weight-600 mb-0">Create Category</h6>
                    </div>
                </div>
            </div>
            <div class="card-body">
                <form method="post">
                    <div class="form-group" >
                        <label asp-for="Name" class="font-weight-600">Name</label>
                        <input  class="form-control"  placeholder="Name" asp-for="Name">
                        <span asp-validation-for="Name" class="text-danger">  </span>
                    </div>
                    <div class="form-group" >
                        <label asp-for="Price" class="font-weight-600">Price</label>
                        <input  class="form-control"  placeholder="Price" asp-for="Price">
                        <span asp-validation-for="Price" class="text-danger">  </span>
                    </div>
                    <div class="form-group">
                        <label asp-for="File" class="font-weight-600">Photo</label>
                        <input class="form-control" placeholder="Photo" asp-for="File" accept="image/*">
                        <span asp-validation-for="File" class="text-danger">  </span>
                    </div>
                    <div class="form-group">
                        <label asp-for="CategoryId" class="font-weight-600">Category</label>
                        <select class="form-control" name="CategoryId">
                            <option value="0">--Select Category-- </option>
                            @foreach (var item in ViewBag.Categories)
                           {
                               if (item.Name == Model.Name)
                               {
                                    <option value="@item.Id" selected>@item.Name</option>

                                }
                                else
                                {
                                    <option value="@item.Id">@item.Name</option>
                                }
                            }
                        </select>
                    </div>
                    
                    <button type="submit" class="btn btn-success">Submit</button>
                    <a asp-action="Index" class="btn btn-light">Cancel</a>
                </form>
            </div>
        </div>
    </div>
</div>